# -----------------------------
# Finding a Motif in DNA
# -----------------------------

# Option 1: Input directly
s = "CAAGTCCCGCTAGTCCCGATTCAGTCCCGTGATGAGTCCCGAGTCCCGGGGGTGCAGTCCCGCAGTCCCGCAGTCCCGGTGCAGTCCCGAATTTAGTCCCGTACATCACTAGTCCCGCTATAGTCCCGCAGTCCCGCGTCGACAGCGGAGTCCCGTGTAGTCCCGAGTCCCGAGTCCCGCCAAGTCCCGGAGTCCCGAGTCCCGCAGTCCCGTCGAACTAGTCCCGAGTCCCGCCAGTCCCGTAAAGGCTAGTCCCGAGTCCCGGTCGAGTCCCGACAACTTGGAGAGTCCCGCGAAGTCCCGACATAGTCCCGAGTCCCGGGCCAGTTAGTCCCGAAGCTTAGTCCCGCTAGTCCCGGATAAGTCCCGCTCAGTCCCGAGTCCCGAGATTTAGTCCCGCGAGTCCCGCAGTCCCGTTAGTCCCGATTAGTCCCGGAGTCCCGAGTCCCGAAAGTCCCGTCAGTCCCGCATAAGTCCCGTCAAGTCCCGAGTCCCGGAGTCCCGTCGAGTCCCGAGTCCCGGGAGTCCCGGAAGCTGAGTCCCGAGTCCCGGTAGTCCCGCTGGCAGTCCCGGGTCATTTCTAATGTCTTCAGCAGTCCCGCAGTCCCGGTAGAGTCCCGAGTCCCGAGTCCCGGTCAGACAGTCCCGGCTAGGTGAGTCCCGAGTCCCGAAGTCCCGAGAAGTCCCGGAGTCCCGAGAGTCCCGGTTGGGATCAGTCCCGTAGTCCCGGGTCATTAGTCCCGGAGTCCCGAGTCCCGAAGTCCCGCAGTCCCGAGTCCCGCTCGGCAGGAGTCCCGTAAGAGTCCCGAAT"  # DNA sequence
t = "AGTCCCGAG"                # motif to search for

def find_motif_positions(sequence, motif):
    positions = []
    for i in range(len(sequence) - len(motif) + 1):
        if sequence[i:i+len(motif)] == motif:
            positions.append(i + 1)  # convert to 1-based indexing
    return positions

# Find all motif positions
result = find_motif_positions(s, t)

# Print space-separated positions (Rosalind format)
print(*result)
